(** Allows JSON-formatted .quiz files to be generated by user *)

open Yojson.Basic.Util
open Quiz

(** [builder ()] executes the quiz builder *)
let builder () =
  ()

(* create: prompt new file name, title, desc, sub/not, num questions,
   answer categories then open vim
   edit: open existing in vim *)

(* open vim at some point *)